In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 =pd.read_csv(파일경로)

아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
인코딩 =pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
인코딩.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [5]:
독립=인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속=인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


In [6]:
x=tf.keras.layers.Input(shape=[4])
h=tf.keras.layers.Dense(8,activation='swish')(x)
h=tf.keras.layers.Dense(8,activation='swish')(h)
h=tf.keras.layers.Dense(8,activation='swish')(h)
y=tf.keras.layers.Dense(3,activation='softmax')(h)
model=tf.keras.models.Model(x,y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [8]:
model.fit(독립,종속,epochs=1000,verbose=0)
model.fit(독립,종속,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0580 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0526 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0462 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0420 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0432 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0488 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0564 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0464 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0502 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0413 - accuracy: 0.9800


In [9]:
model.predict(독립[0:5])

array([[9.9999988e-01, 2.0588011e-08, 9.3546525e-08],
       [9.9999964e-01, 2.7581305e-07, 1.7807540e-07],
       [9.9999976e-01, 7.2087090e-08, 1.6968576e-07],
       [9.9999988e-01, 1.2278753e-07, 3.0859137e-08],
       [9.9999988e-01, 1.1667878e-08, 6.4217048e-08]], dtype=float32)

In [10]:
종속[0:5]

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

In [11]:
model.predict(독립[-5:])

array([[2.01574952e-08, 7.75317894e-04, 9.99224663e-01],
       [3.92948039e-08, 1.22571746e-02, 9.87742782e-01],
       [1.00169295e-07, 1.18620535e-02, 9.88137901e-01],
       [1.03712402e-07, 3.69846501e-04, 9.99629974e-01],
       [7.83333462e-07, 6.51492104e-02, 9.34849977e-01]], dtype=float32)

In [12]:
종속[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [ ]:
model.get_weights()

[array([[  4.323351 ,   1.5076023,  -0.9796379],
        [  9.257961 ,   1.3455493,  -2.7338054],
        [-13.615414 ,  -2.341413 ,   2.4305263],
        [-16.93677  ,  -3.823127 ,   5.4346004]], dtype=float32),
 array([ 6.4006467,  5.6529946, -6.009102 ], dtype=float32)]