In [26]:
import pandas as pd
import tensorflow as tf

In [27]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 =pd.read_csv(파일경로)

아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [28]:
인코딩 =pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [29]:
인코딩.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [32]:
독립=인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속=인코딩[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape,종속.shape)

(150, 4) (150, 3)


In [34]:
x=tf.keras.layers.Input(shape=[4])
y=tf.keras.layers.Dense(3,activation='softmax')(x)
model=tf.keras.models.Model(x,y)
model.compile(loss='categorical_crossentropy',metrics='accuracy')

In [37]:
model.fit(독립,종속,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0538 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0536 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0534 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0536 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0534 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0533 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0533 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0535 - accuracy: 0.9800


In [38]:
model.predict(독립[0:5])

array([[1.0000000e+00, 2.5430233e-11, 2.1694105e-24],
       [1.0000000e+00, 2.3338922e-09, 2.5172839e-21],
       [1.0000000e+00, 2.7275177e-10, 1.3276638e-22],
       [1.0000000e+00, 7.6021136e-09, 1.8532075e-20],
       [1.0000000e+00, 1.5275836e-11, 1.1113535e-24]], dtype=float32)

In [39]:
종속[0:5]

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

In [42]:
model.predict(독립[-5:])

array([[7.2252969e-23, 3.9026581e-03, 9.9609739e-01],
       [4.0443340e-21, 1.9468816e-02, 9.8053116e-01],
       [1.9876822e-20, 3.6886856e-02, 9.6311319e-01],
       [2.4975070e-23, 2.2190551e-03, 9.9778098e-01],
       [3.4360909e-19, 8.1217326e-02, 9.1878265e-01]], dtype=float32)

In [43]:
종속[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [44]:
model.get_weights()

[array([[  4.323351 ,   1.5076023,  -0.9796379],
        [  9.257961 ,   1.3455493,  -2.7338054],
        [-13.615414 ,  -2.341413 ,   2.4305263],
        [-16.93677  ,  -3.823127 ,   5.4346004]], dtype=float32),
 array([ 6.4006467,  5.6529946, -6.009102 ], dtype=float32)]